title: GDG Pisa
description: "Il Google Developer Group di Pisa è una community dove le persone possono condividere liberamente le proprie idee, le proprie conoscenze ed esperienze in campo tecnologico.
Non è richiesta alcuna competenza particolare, se sei semplicemente interessato alla tecnologia non ti resta che entrare in contatto con noi :D"
author: GDG Pisa
logo: /static/img/logo-adesivo.png
github: https://github.com/gdgpisa
about: Google Developer Group Pisa

baseurl: ""
url: "https://gdgpisa.it"

allowsearch: true

# disqus_shortname: aboutashu
google_analytics: UA-109677042-1

share:
  twitter_username: \gdgpisa
  fb_appid: 000000000000

plugins: [jekyll-paginate-v2, jekyll-gist, jekyll-redirect-from, jekyll-workbox-plugin,jekyll-workbox-plugin]

enableTags: true
tagarray: []
markdown: kramdown

#pagination config
permalink: /blog/:year/:month/
pagination:
  paginate_path: "/page:num/"
  enabled: true
  per_page: 10
  sort_reverse: true
  sort_field: 'date'
  title: ':title'
  trail:
    before: 2
    after: 2

workbox:
  sw_src_filepath: sw.js # Optional
  sw_dest_filename: sw.js # Optional
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
